services:
  - type: web
    name: tic-tac-toe-server
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/server
    envVars:
      - key: RUST_LOG
        value: info
